#!/usr/bin/env python3
"""組織別 軸重みプロファイルの定期更新 (Issue #81, Phase1)。

組織が 50 ペア以上のペアワイズフィードバックを蓄積したら、ペアワイズロジ回帰
(#16) で組織別の軸重みプロファイルを自動更新する。LoRA 作成までのコールドスタート期
および小規模組織のメイン適合手段。

処理フロー (組織ごと):
  1. フィードバック DB から読み出し (consent_to_train=false は skip)
  2. ペア数 < 閾値 (既定 50) は skip
  3. build_feedback_dataset (#80) で組織の weights/pairs.jsonl を生成
  4. regress_weights (#16) のペアワイズロジ回帰で軸重み w を推定
  5. eval: 回帰重み vs 固定重みの pairwise accuracy を比較
  6. 回帰が固定より 0.02 以上悪化 → rollback (書き出さず alert)
  7. config/weights_profile/{org_id}.yaml を書き出し、履歴を記録

推論時の重み選択 (config/weights_profile/{org_id}.yaml の参照) は #83 で実装済み。

起動:
  # cron 想定 (全組織): 毎日 03:00 JST など
  python scripts/update_weight_profiles.py
  # 単一組織 (API トリガー /api/admin/retrain_weights からも呼ばれる)
  python scripts/update_weight_profiles.py --org-id org_001
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))
sys.path.insert(0, str(REPO_ROOT))

from scripts.build_feedback_dataset import (  # noqa: E402
    build_for_org,
    load_feedback_from_db,
    load_meeting_index,
)
from scripts.regress_weights import (  # noqa: E402
    SCORE_KEYS,
    default_weight_vector,
    fit_pairwise_logistic,
    load_pairs_with_scores,
    normalize_weights,
    pairwise_accuracy,
)

STAGE1_MIN_PAIRS = 50  # Epic #77 段階1: 50 ペア以上で重みプロファイル更新
ROLLBACK_MARGIN = 0.02  # 回帰が固定より これ以上悪化したら採用しない
DEFAULT_MEETINGS_DIR = REPO_ROOT / "data" / "stored_meetings"
DEFAULT_OUT_ROOT = REPO_ROOT / "data" / "feedback"
DEFAULT_PROFILE_DIR = REPO_ROOT / "config" / "weights_profile"
ORG_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$")


def validate_org_id(org_id: str) -> None:
    """org_id をファイルシステム上の子パスとして安全に使える形式へ制限する。"""
    if not ORG_ID_RE.fullmatch(org_id):
        raise ValueError(f"invalid org_id for filesystem path: {org_id!r}")


def safe_child_path(root: Path, *parts: str) -> Path:
    """root 配下に収まる子パスだけを返す。"""
    resolved_root = root.resolve()
    candidate = resolved_root.joinpath(*parts).resolve()
    candidate.relative_to(resolved_root)
    return candidate


def enumerate_consenting_orgs() -> list[str]:
    """フィードバック DB から consent_to_train=true の組織 ID を列挙する。"""
    from sqlmodel import Session, select

    from app.store.db import get_engine
    from app.store.feedback_models import Organization

    with Session(get_engine()) as session:
        rows = session.exec(select(Organization).where(Organization.consent_to_train)).all()
    return [o.org_id for o in rows]


def render_profile_yaml(
    org_id: str, w: np.ndarray, n_pairs: int, acc_reg: float, acc_fixed: float
) -> str:
    """config.yaml の weights セクションと同形式の組織別プロファイルを作る。"""
    lines = [
        f"# {org_id} の重みプロファイル (auto-generated by scripts/update_weight_profiles.py, do not edit)",
        f'generated_at: "{datetime.now(tz=UTC).isoformat()}"',
        f"n_pairs: {n_pairs}",
        "weights:",
        *[f"  {k}: {round(float(v), 3)}" for k, v in zip(SCORE_KEYS, w, strict=True)],
        # 減点軸は Phase1 では回帰せず 1.0 固定 (推論側 #83 は weights のみ参照)。
        "penalties:",
        "  duplication: 1.0",
        "  verbosity: 1.0",
        "  off_topic: 1.0",
        "  unsupported_assertion: 1.0",
        "  override: 0.5",
        "eval:",
        f"  pairwise_acc: {round(acc_reg, 4)}      # baseline {round(acc_fixed, 4)}",
        "  spearman: null            # gold アノテ (#5) + eval ハーネス (#4) が必要",
    ]
    return "\n".join(lines) + "\n"


def _append_history(profile_dir: Path, record: dict[str, Any]) -> None:
    profile_dir.mkdir(parents=True, exist_ok=True)
    with (profile_dir / "history.jsonl").open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def update_org_profile(
    org_id: str,
    *,
    since: datetime | None = None,
    meetings_dir: Path = DEFAULT_MEETINGS_DIR,
    out_root: Path = DEFAULT_OUT_ROOT,
    profile_dir: Path = DEFAULT_PROFILE_DIR,
    min_pairs: int = STAGE1_MIN_PAIRS,
    version: str = "v1",
    l2: float = 1.0,
    lr: float = 0.1,
    iters: int = 3000,
    seed: int = 3407,
) -> dict[str, Any]:
    """単一組織の重みプロファイルを更新する。status を含む結果 dict を返す。

    org_id は単一・必須 (組織混在禁止)。consent_to_train=false / 閾値未満 / 回帰悪化は
    プロファイルを書き出さず status で理由を返す。
    """
    validate_org_id(org_id)

    consent, pairwise_rows, axis_rows = load_feedback_from_db(org_id, since)
    if not consent:
        return {"org_id": org_id, "status": "skipped_no_consent"}

    n_feedback_pairs = len(pairwise_rows)
    if n_feedback_pairs < min_pairs:
        return {
            "org_id": org_id,
            "status": "skipped_below_threshold",
            "n_pairs": n_feedback_pairs,
            "min_pairs": min_pairs,
        }

    # #80 で組織の weights/pairs.jsonl (scores_a/scores_b 同梱) を生成。
    meeting_index = load_meeting_index(meetings_dir)
    build_for_org(
        org_id,
        consent=consent,
        pairwise_rows=pairwise_rows,
        axis_rows=axis_rows,
        meeting_index=meeting_index,
        out_root=out_root,
        version=version,
        max_pairs_per_feedback=20,
        val_ratio=0.0,
        seed=seed,
    )
    pairs_path = safe_child_path(out_root, org_id, "weights", version, "pairs.jsonl")
    pairs = load_pairs_with_scores(pairs_path)
    if not pairs:
        return {
            "org_id": org_id,
            "status": "skipped_no_resolved_pairs",
            "n_pairs": n_feedback_pairs,
        }
    n_resolved_pairs = len(pairs)
    if n_resolved_pairs < min_pairs:
        return {
            "org_id": org_id,
            "status": "skipped_below_resolved_threshold",
            "n_pairs": n_resolved_pairs,
            "n_feedback_pairs": n_feedback_pairs,
            "min_pairs": min_pairs,
        }

    diffs = np.array([np.array(win) - np.array(lose) for win, lose in pairs], dtype=float)
    w = normalize_weights(fit_pairwise_logistic(diffs, l2=l2, lr=lr, iters=iters, nonneg=True))
    acc_reg = pairwise_accuracy(diffs, w)
    acc_fixed = pairwise_accuracy(diffs, default_weight_vector())

    result: dict[str, Any] = {
        "org_id": org_id,
        "n_pairs": n_resolved_pairs,
        "acc_regressed": round(acc_reg, 4),
        "acc_fixed": round(acc_fixed, 4),
    }

    # 回帰重みが固定より明確に悪い → 採用しない (rollback)。
    if acc_reg < acc_fixed - ROLLBACK_MARGIN:
        result["status"] = "rolled_back"
        _append_history(profile_dir, {**result, "ts": datetime.now(tz=UTC).isoformat()})
        return result

    profile_path = safe_child_path(profile_dir, f"{org_id}.yaml")
    profile_path.parent.mkdir(parents=True, exist_ok=True)
    profile_path.write_text(
        render_profile_yaml(org_id, w, n_resolved_pairs, acc_reg, acc_fixed), encoding="utf-8"
    )
    result["status"] = "updated"
    result["profile"] = str(profile_path)
    _append_history(profile_dir, {**result, "ts": datetime.now(tz=UTC).isoformat()})
    return result


def run(args: argparse.Namespace) -> list[dict[str, Any]]:
    since = datetime.fromisoformat(args.since) if args.since else None
    kwargs = dict(
        since=since,
        meetings_dir=Path(args.meetings_dir),
        out_root=Path(args.out_root),
        profile_dir=Path(args.profile_dir),
        min_pairs=args.min_pairs,
        version=args.version,
        l2=args.l2,
        lr=args.lr,
        iters=args.iters,
        seed=args.seed,
    )
    org_ids = [args.org_id] if args.org_id else enumerate_consenting_orgs()
    results = []
    for org_id in org_ids:
        r = update_org_profile(org_id, **kwargs)
        results.append(r)
        print(
            f"[{org_id}] {r['status']} "
            + json.dumps(
                {k: v for k, v in r.items() if k not in ("org_id", "status")}, ensure_ascii=False
            )
        )
    updated = sum(1 for r in results if r["status"] == "updated")
    print(f"\n対象 {len(results)} 組織 / 更新 {updated} 件")
    return results


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--org-id", default=None, help="単一組織のみ更新 (未指定なら全 consenting 組織)")
    p.add_argument("--since", default=None, help="この日時以降のフィードバックのみ (ISO 8601)")
    p.add_argument("--meetings-dir", default=str(DEFAULT_MEETINGS_DIR))
    p.add_argument("--out-root", default=str(DEFAULT_OUT_ROOT))
    p.add_argument("--profile-dir", default=str(DEFAULT_PROFILE_DIR))
    p.add_argument("--min-pairs", type=int, default=STAGE1_MIN_PAIRS)
    p.add_argument("--version", default="v1")
    p.add_argument("--l2", type=float, default=1.0)
    p.add_argument("--lr", type=float, default=0.1)
    p.add_argument("--iters", type=int, default=3000)
    p.add_argument("--seed", type=int, default=3407)
    return p


def main() -> None:
    run(build_arg_parser().parse_args())


if __name__ == "__main__":
    main()
